@host = http://localhost:9200

PUT {{host}}/ztm
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_point"
      },
      "time": {
        "type": "date" 
      }
    }
  }
}

